[workspace]
members = [
    "adapters/ark-groth16",
    "adapters/bulletproofs-range",
    "adapters/jellyfish-plonk",
    "crates/adapter-sdk",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
ark-bn254 = "0.6.0"
ark-ff = "0.6.0"
ark-groth16 = "0.6.0"
ark-relations = "0.6.0"
ark-r1cs-std = "0.6.0"
ark-serialize = "0.6.0"
ark-std = "0.6.0"
rayon = "1.11.0"
